export enum ProjectSortProperty {
  ID = "ID",
  NAME = "NAME",
  CODE_NAME = "CODE_NAME",
  START_DATE = "START_DATE",
  END_DATE = "END_DATE",
  CREATE_DATE = "CREATE_DATE",
  LAST_MODIFICATION_DATE = "LAST_MODIFICATION_DATE",
  CLIENT = "CLIENT"
}
