package com.wojciechdm.programmers.user.registration;

import lombok.*;

@AllArgsConstructor
@Getter
enum UserSqlStatementParameter {
  INSERT_USER_FIRST_NAME(1),
  INSERT_USER_LAST_NAME(2),
  INSERT_USER_AGE(3),
  INSERT_USER_DATE_OF_BIRTH(4),
  INSERT_USER_ADDRESS_ID(5),
  INSERT_USER_TITLE(6),
  INSERT_ADDRESS_CITY(1),
  INSERT_ADDRESS_STREET(2),
  INSERT_ADDRESS_NUMBER(3),
  INSERT_ADDRESS_ZIPCODE(4),
  INSERT_ADDRESS_COUNTRY(5),
  INSERT_USER_LOGIN_USERNAME(1),
  INSERT_USER_LOGIN_PASSWORD(2),
  INSERT_USER_LOGIN_USER_DATA_ID(3),
  INSERT_USER_ROLE_ROLE(1),
  INSERT_USER_ROLE_USER_ID(2),
  SELECT_USER_ID(1),
  SELECT_ADDRESS_ID(1),
  SELECT_USER_LOGIN_USERNAME(1),
  SELECT_USER_LOGIN_ID(1);

  private int parameterNumber;
}
